engine/db_id/models.py
from db_id import db, ma
#from flask import current_app as app
from datetime import datetime
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

class Item(db.Model):
    __tablename__ = 'item'
    __searchable__ = ['title']

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), unique=True, nullable=False)
    comment = db.Column(db.Text, nullable=False)
    created_on = db.Column(db.DateTime, server_default=db.func.now())
    updated_on = db.Column(db.DateTime, server_default=db.func.now(), server_onupdate=db.func.now())
    date_modified = db.Column(db.DateTime, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp())

    def __init__(self, title, comment):
        self.title = title
        self.comment = comment

    def __repr__(self):
        return f"Post('{self.title}', '{self.created_on}')"

# Items Schema
class ItemSchema(ma.Schema):
    class Meta:
        fields = ('id', 'title', 'comment', 'created_on', 'updated_on', 'date_modified')


# Init schema
item_schema = ItemSchema()
items_schema = ItemSchema(many=True)

# results = BlogPost.query.whoosh_search('cool')
# https://medium.com/@rajatrs5054/scout-vs-whoosh-for-full-text-search-in-python-5f1015591a62

engine/db_id/items/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class ItemForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    comment = TextAreaField('Comment', validators=[DataRequired()])
    submit = SubmitField('Save')

engine/db_id/__init__.py
import sys
import os
from flask import Flask
from flask_cors import CORS
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
from db_id.config import Config
from flask_msearch import Search


db = SQLAlchemy()
ma = Marshmallow()
#search = Search()

def create_app(config_class=Config):
    if getattr(sys, 'frozen', False):

        # db_path = os.path.join(os.path.dirname(__file__), '../app_data.db')
        # only run as an executable
        template_folder = os.path.join(sys._MEIPASS, os.path.dirname(__file__), '../templates')
        static_folder = os.path.join(sys._MEIPASS, os.path.dirname(__file__), '../static')

        print(template_folder)
        print(static_folder)

        app = Flask(__name__, template_folder=template_folder, static_folder=static_folder)

    else:
        app = Flask(__name__)

    app.config.from_object(Config)

    db.init_app(app)
    with app.app_context():
        db.create_all()
    ma.init_app(app)
    #search.init_app(app)

    #Cors support
    # TODO:: do better
    ORIGINS = [
        'http://localhost:8080',  # React
        'http://127.0.0.1:8080',  # React
    ]

    CORS(app, resources={r'/*': {'origins': ORIGINS}}, supports_credentials=True)

    #Cors support

    from db_id.items.routes import items
    from db_id.main.routes import main

    app.register_blueprint(items)
    app.register_blueprint(main)


    return app

engine/db_id/items/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, jsonify)
from flask_marshmallow import Marshmallow
import json
from db_id import db
from db_id.items.forms import ItemForm
from db_id.models import Item, item_schema, items_schema

items = Blueprint('items', __name__)


@items.route('/item/new', methods=['GET', 'POST'])
def new_item():
    form = ItemForm()
    if form.validate_on_submit():
        item = Item(title=form.title.data, comment=form.comment.data)
        db.session.add(item)
        db.session.commit()
        flash('Item created', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_item.html', title='New Item',
                           form=form, legend='New Item')


@items.route('/item/<int:item_id>', methods=['GET', 'POST'])
def item(item_id):
    item = Item.query.get_or_404(item_id)
    return render_template('item.html', title=item.title, item=item)


@items.route('/item/<int:item_id>/update', methods=['GET', 'POST'])
def update_item(item_id):
    item = Item.query.get_or_404(item_id)
    form = ItemForm()

    if form.validate_on_submit():
        item.title = form.title.data
        item.comment = form.comment.data
        db.session.commit()
        flash('Item updated', 'success')
        return redirect(url_for('items.item', item_id=item.id))

    elif request.method == 'GET':
        form.title.data = item.title
        form.comment.data = item.comment

    return render_template('create_item.html', title='Update Item',
                           form=form, legend='Update Item')


@items.route('/items-list', methods=['GET'])
def items_list():
    page = request.args.get('page', 1, type=int)
    items = Item.query.order_by(Item.created_on.desc()).paginate(page=page, per_page=5)
    return jsonify(items)


# api create new item
@items.route('/api/new-item', methods=['POST'])
def api_new_item():
    title = request.json['title']
    comment = request.json['comment']

    item = Item(title, comment)
    db.session.add(item)
    db.session.commit()
    return item_schema.jsonify(item)


# api update item
@items.route('/api/item/<id>', methods=['PUT'])
def api_update_item(id):
    item = Item.query.get(id)
    title = request.json['title']
    comment = request.json['comment']

    item.title = title
    item.comment = comment
    db.session.commit()
    return item_schema.jsonify(item)


# api get items list
@items.route('/api/items-list', methods=['GET'])
def api_items_list():
    all_items = Item.query.all()
    result = items_schema.dump(all_items)
    print(result)
    return jsonify(result)


# api get single item
@items.route('/api/item/<id>', methods=['GET'])
def api_get_item(id):
    item = Item.query.get(id)
    return item_schema.jsonify(item)


# api delete single item
@items.route('/api/item/<id>', methods=['DELETE'])
def api_delete_item(id):
    item = Item.query.get(id)
    db.session.delete(item)
    db.session.commit()
    return item_schema.jsonify(item)


# Search endpoint
@items.route('/api/search-results', methods=['GET', 'POST'])
def api_search_results():
    #num_posts = min(request.args.get('limit', 10), 50)
    data = json.loads(request.data)
    search_value = "%{}%".format(data.get('text'))
    page = data.get('page')
    items_pp: int = 50
    results = Item.query.order_by(Item.id.asc()).filter(Item.title.like(search_value)).paginate(per_page=items_pp, page=page)
    result = items_schema.dump(results.items)

    item_l = {
        'page': results.per_page,
        'pages': list(results.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)),
        'items': result,
        'items_pp': results.per_page
    }

    response = jsonify(item_l)
    response.headers.add('Access-Control-Allow-Origin', '*')
    return response

engine/db_id/main/routes.py
from flask import render_template, request, Blueprint
from db_id.models import Item


main = Blueprint('main', __name__)

@main.route('/')
def home():
    page = request.args.get('page', 1, type=int)
    items = Item.query.order_by(Item.created_on.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', items=items)


@main.route('/about')
def about():
    return render_template('about.html', title = 'About')

engine/db_id/templates/about.html
{% extends 'layout.html' %}
{% block content %}
{% endblock content %}

engine/db_id/templates/create_item.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
    <div id="create_item_form"> Loading form ....</div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.comment.label(class="form-control-label") }}
                {% if form.comment.errors %}
                    {{ form.comment(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.comment.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.comment(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>

{% endblock content %}

{% block javascript %}
    <script src="{{ url_for('static', filename='libs/build/create_item_form.bundle.js') }}">

    </script>
{% endblock javascript %}

engine/db_id/templates/home.html
{% extends 'layout.html' %}
{% block content %}

<h1> App Home !!</h1>
<div id="home_search"> Loading app .....</div>
    {% for item in items.items %}
        <article class="media content-section">
            <div class="media-body">
              <div class="article-metadata">
                <small class="text-muted">{{ item.updated_on.strftime('%Y-%m-%d') }}</small>
              </div>
              <h2><a class="article-title" href="{{ url_for('items.item', item_id=item.id) }}">{{ item.title }}</a></h2>
              <p class="article-content">{{ item.comment }}</p>
            </div>
          </article>
    {% endfor %}
    {% for page_num in items.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
          {% if items.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
      {% else %}
          ...
      {% endif %}
    {% endfor %}
{% endblock content %}

{% block javascript %}
    <script src="{{ url_for('static', filename='libs/build/home_search.bundle.js') }}">

    </script>
{% endblock javascript %}

engine/db_id/templates/item.html
{% extends 'layout.html' %}
{% block content %}

<article class="media content-section">
        <div class="media-body">
          <div class="article-metadata">
            <small class="text-muted">{{ item.created_on.strftime('%Y-%m-%d') }}</small>
          </div>
            <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('items.update_item', item_id=item.id)}}"> Update </a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>

                </div>
          <h2 class="article-title">{{ item.title }}</h2>
          <p class="article-content">{{ item.comment }}</p>
        </div>
</article>

{% endblock content %}

engine/db_id/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='libs/build/main.css') }}">

    {% if title %}
        <title>DB ID - {{ title }}</title>
    {% else %}
        <title>DB ID</title>
    {% endif %}
</head>
<body class="main-app">
    <div class="main-nav">
        <header class="site-header">

            <div class="app-header navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('items.new_item') }}">Add Item</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">Import</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
        </header>
    </div>

    <div class="main-content">
        <main role="main" class="app-container">
            <div class="row">
                <div class="col-md-8">
                    {% with messages = get_flashed_messages(with_categories=true)  %}
                    {% if messages %}

                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                    {% endfor %}

                    {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
                <div class="col-md-4">
                    <div class="content-section">
                        <h3>Our Sidebar</h3>
                        <p class='text-muted'>You can put any information here you'd like.
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                        </p>
                    </div>
                </div>
            </div>
        </main>

    </div>

    <footer>
        {% block javascript %}
	        <script src="{{ url_for('static', filename='libs/build/main.bundle.js') }}">

            </script>

        {% endblock %}
    </footer>
</body>
</html>